### ISSUE TITLE
SSM States breaking on browser zoom

### ISSUE THREAD

**Issue by amartinezatcpo** [SimpleStateManager/SimpleStateManager#20]
When FF and IE are zoomed in or out, ssm.getBroswerWidth() value returned is 0 which prevents the states from firing correctly.

**Comment by jonathan-fielding** [comment]
So the code that causes this bug is the code that supports legacy Internet Explorer, unfortunately doesnt look like I can easily fix that SO I will be discontinuing support for legacy Internet Explorer in SSM3 which I expect to be ready by mid may.

**Comment by jonathan-fielding** [comment]
The getWidth method is completely gone from SSM3

**Comment by jonathan-fielding** [comment]
and SSM3 will feature support for the full breadth of MQL4 spec

**Comment by jonathan-fielding** [comment]
fixed in 2.4.1 thanks to jdbryner
