### ISSUE TITLE
onEnter not firing when crossing a min-width threshold

### ISSUE THREAD

**Issue by bw1984** [SimpleStateManager/SimpleStateManager#31]
when resizing the browser window to test, moving from somewhere in the 'tablet' range into 'desktop' correctly triggers the 'enter desktop' log, but when crossing over the threshold from mobile to tablet the event ("enter tablet") is not triggered. 

resizing "downwards" across the thresholds seems to work correctly as expected, as does resizing "upwards" into a state which only has a min-width query set, but it seems that any state which has both a min-width and max-width set fails to trigger when crossing over the min-width threshold

this bug is actually reproducible using the first example on the API page (http://www.simplestatemanager.com/api.html). If you drag your browser window in and out and you should see that crossing over from 'mobile' to 'tablet' state doesn't trigger the event. This is the case for me in both chrome and firefox (both latest)

**Comment by bw1984** [comment]
just performed a quick test and found an easy workaround;

the following isn't functioning as expected;
query: '(min-width: 768px)',
query: '(max-width: 1023px)',

but if you combine the upper and lower ranges into 1 query it works as expected.
query: '(min-width:768px) and (max-width:1023px)',

**Comment by jonathan-fielding** [comment]
Hi @bw1984, looks like rather than find a bug in the library you have found a bug in the documentation, will update the docs, thanks

**Comment by jonathan-fielding** [comment]
Ok that is fixed http://www.simplestatemanager.com/api.html

**Comment by jonathan-fielding** [comment]
Thank you for bringing this to my attention though, lots of people could have had same confusion
