### ISSUE TITLE
min-height and min-width or max-height and max-width

### ISSUE THREAD

**Issue by petebarr** [SimpleStateManager/SimpleStateManager#32]
Hi Jonathan,

Does this work with query combinations of width and height? e.g. query: '(max-height: 768px) and (max-width: 1200px)', Do you have an example if you do? I can't seem to get it to work.

Cheers!

**Comment by jonathan-fielding** [comment]
Hi

This should work as you expect, to illustrate I have thrown together a JSbin, if you resize browser to (max-width: 767px) and (max-height: 500px) the jsbin console will log 'enter mobile'
http://jsbin.com/wikonayese/edit?html,console,output

If this still doesn't work please send me a jsbin link showing me the problem and i will look into it

Thanks

Jonathan

**Comment by petebarr** [comment]
Cheers very much Jonathan, I was getting muddled up with:

ssm.addConfigOption({
    name: "minHeight",
    test: function(){
        return true;
    }
});

Really appreciate it!!

**Comment by jonathan-fielding** [comment]
config options are something entirely different and are used for adding new kind of tests beyond simply media queries :D glad that helped
