### ISSUE TITLE
SSM 3.x and IE8 (polyfills option)

### ISSUE THREAD

**Issue by humanaut** [SimpleStateManager/SimpleStateManager#33]
I hate to be "that IE guy", but I was wondering if I could get a bit more clarification regarding the IE8 support option #1, using the two polyfills.

I am currently using Respondjs matchMedia polyfill and the mozilla bind polyfill  (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_objects/Function/bind)

I am loading these via conditional comments in my Drupal template. 

I am receiving these two errors and am not sure if this is related to the bind not working or something else. 

```
Object doesn't support this property or method - ssm.min.js
'ssm' is undefined
````

![image](https://cloud.githubusercontent.com/assets/3498525/9588332/a4b31426-4ff5-11e5-93e5-791f8c42a6ea.png)

I just have one SSM state which is outputting to console, not much going on. I get these errors whether or not I am loading the matchMedia or bind polyfills.

Any help would be appreciated.

Thanks

**Comment by jonathan-fielding** [comment]
Hi

The matchMedia polyfill in RespondJS wasn't a complete implementation when I looked at it last year, it is covers what it needs itself but not what third party libraries need, I would recommend a full match media polyfill such as https://github.com/paulirish/matchMedia.js/ which supports add and remove listener

Any more questions regarding this, just reopen ticket and leave a reply and I will get back to you as quick as I can

Thanks

Jonathan
