### ISSUE TITLE
SSM 3.x and IE8 (polyfills option) (revisited)

### ISSUE THREAD

**Issue by humanaut** [SimpleStateManager/SimpleStateManager#34]
Hello! Sorry to make a new ticket (don't think I can re-open an existing one if I am not a repo collaborator) 

Original ticket: https://github.com/SimpleStateManager/SimpleStateManager/issues/33#issuecomment-136730370

I have tested matchMedia (within the respondjs bower package, there are actually a matchMedia.js and matchMedia.addListener.js files also.

I also downloaded the matchMedia polyfill on it's own (they are probably the same, I did not compare the code of the two). 

I unfortunately get the same errors in IE8. 

![image](https://cloud.githubusercontent.com/assets/3498525/9608351/ff3bf7cc-509b-11e5-9076-f0c0cd9669aa.png)

I am not sure if it's the order the scripts that must be loaded (js is not my strong point) but I've tried every order I can think of. 

This is not a huge deal as we don't support IE8 in general, but if we do I was hoping to not have to change SSM version's and have developers change how they write SSM statements, even though it's a very minimal difference between the two (I would just have to educate developers).

Again, no big deal if there is not a simple solution, just hoping that I have made a noob mistake and someone has picked up on that. 

Here is my implementation:

![image](https://cloud.githubusercontent.com/assets/3498525/9608435/4f804684-509c-11e5-8a1a-4d2f9fb56461.png)

**Comment by jonathan-fielding** [comment]
Hi, 

So I had to spend a few hours investigating this which has been spread across the week, but yes it will work with IE8 and 9 but you have to get the correct polyfills, the most popular polyfill !== best in this case

Polyfills I used

//Add event listener
https://gist.github.com/eirikbacker/2864711/946225eb3822c203e8d6218095d888aac5e1748e

//Bind
https://github.com/kdimatteo/bind-polyfill

//MatchMedia
https://github.com/weblinc/media-match

With this in place (i copied source of all into jsbin for ease)  it works (tested in IE8, not got a IE9 vm but assume it will work there too)
http://jsbin.com/cudufaposu/1/edit?html,output

Hope this helps

Jonathan
