### ISSUE TITLE
Typo in the docs

### ISSUE THREAD

**Issue by codedbypaul** [SimpleStateManager/SimpleStateManager#35]
I think there's a typo in the docs. In the Defining your first state example it says:

```query: '(min-width: 767px)',```

Is this supposed to be max-width?

**Comment by jonathan-fielding** [comment]
Hey Paul, 

Yes you would be correct, I will fix that now

Thanks

Jonathan

**Comment by jonathan-fielding** [comment]
Thats fixed now, thanks again
