### ISSUE TITLE
removeAllStates() doesn't remove the event listeners

### ISSUE THREAD

**Issue by erwinsmit** [SimpleStateManager/SimpleStateManager#36]
Hi,

Thanks for the great work on this project.
I'm having this issue where event listeners are not removed after calling removeAllStates().

I have created an example here: https://jsbin.com/yuvavu/3/edit
You can see, that on resizing the screen it logs correctly 'large-above' or 'medium-above'.
However, after clicking on 'Remove states' it still keeps logging these messages. 

When I log out all the states (before and after I remove them), I notice that the listener property is undefined. So this value in the destroy method is undefined too, https://github.com/SimpleStateManager/SimpleStateManager/blob/master/src/ssm.js#L128. 

Hope this makes sense, thanks in advance for looking into this!

**Comment by jonathan-fielding** [comment]
Hey, @erwinsmit 

I believe this is fixed if you want to try running your example again you will see the code in master now runs as expected. If your happy that the bug is now fixed I will do a release.

Thanks for raising the ticket, was a good spot :+1: 

Thanks

Jonahtan

**Comment by erwinsmit** [comment]
Hi @jonathan-fielding 

Thanks for fixing this on such short notice, it seems to work great now :+1:

**Comment by jonathan-fielding** [comment]
@erwinsmit ok thats published to NPM now

**Comment by jonathan-fielding** [comment]
Thanks for your help
