### ISSUE TITLE
Minor: Bower instructions on main site

### ISSUE THREAD

**Issue by willthemoor** [SimpleStateManager/SimpleStateManager#37]
Just a note that the website (vs the README here) has this instruction for bower: `bower install simplestatemanager` (lowercase). That actually comes up 'not found': 

```
$ bower install simplestatemanager
bower ENOTFOUND     Package simplestatemanager not found
```

```bash
$ bower search simplestatemanager
Search results:
    SimpleStateManager git://github.com/jonathan-fielding/SimpleStateManager.git
    ssm git://github.com/SimpleStateManager/SimpleStateManager.git
    ssm-colorbox git://github.com/SimpleStateManager/ssm-colorbox.git
```

The readme here at the repo has the correct command `bower install SimpleStateManager`. 

On that same note, for servers that do care about capitalization, the following instruction from the site would also generate an error: `<script src="bower_components/simplestatemanager/dist/ssm.min.js"></script>` since bower installs it into `/SimpleStateManager/`

Not at all a big deal but thought I'd share it anyway. Thanks for ssm!

**Comment by jonathan-fielding** [comment]
Hello

This is a pretty major issue as it potentially blocked potential users using SSM, I wanted to fix it in a way that suited the bower ecosystem so I looked at how other packages were named and saw its best practice to use lowercase anyway. I have therefore republished the project as simplestatemanager so it is now avaliable under the correct name, I left the capitalised version available 

Thanks

Jonathan
