### ISSUE TITLE
Minor: Changelog shows 3.1.0 as Feb 2015, should be Feb 2016

### ISSUE THREAD

**Issue by wlanni** [SimpleStateManager/SimpleStateManager#38]
So minor it verges on nitpicky.

Changelog is off by a year for version 3.1.0 -- confused me when I looked at it as I seemed to remember that I had requested that functionality, and I didn't work at my current spot back in Feb '15.

Anyway, that's all.

**Comment by jonathan-fielding** [comment]
Not first typo I had reported recently, thanks 😀.  Will fix when next on computer.

Jonathan

**Comment by jonathan-fielding** [comment]
Ok finally got round to fixing this, 

Thanks

Jonathan
