### ISSUE TITLE
Bug with IE11?

### ISSUE THREAD

**Issue by christianromeni** [SimpleStateManager/SimpleStateManager#39]
Somehow the latest version does not seem to work with IE11.
Or maybe I'm doing something wrong...?

![image](https://cloud.githubusercontent.com/assets/1358040/16152405/0bbdc0da-34a2-11e6-94d0-549265d61e4c.png)

This happens on every pageload.

My script looks like this:

```
    ssm.addState({
      id: 'default',
      onEnter: function(){
        console.log('enter default');
      }
    });
```

Can someone reproduce this?

**Comment by jonathan-fielding** [comment]
Good Spot

Ok so just did some investigation and it appears their is an issue in IE that it doesn't take an empty string for a media query list however a media expression which is always true is valid. Will push a fix

Thanks

Jonathan

**Comment by jonathan-fielding** [comment]
Hello

So I have pushed a fix up to Git and to NPM now, you will need version 3.1.2

Thanks

Jonathan
